apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    template.openshift.io/bindable: "false"
  name: namespace-java-tekton-resources
  namespace: openshift
objects:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: build-and-deploy-java
  spec:
    params:
    - name: app-name
      type: string
      description: The application name
    - name: build-type
      type: string
      description: "Selected build type: quarkus-jvm, quarkus-fast-jar, quarkus-native, spring-boot"
    - name: deploy-type
      type: string
      description: "Selected deploy type: rolling-replace, blue-green, simple"
    - name: git-repo-url
      type: string
      description: "Git Repository URL"
    - name: git-checkout
      type: string
      description: "Git code to checkout, either a branch name or a commit sha.  Determined by the value of clone-type"
      default: "main"
    - name: clone-type
      type: string
      description: "The type of git clone: sha, branch"
      default: "branch"
    - name: config-git-path
      type: string
      description: "Config Git Path"
      default: "/deploy-config"
    tasks:
    - name: build
      taskRef:
        name: build-java
        kind: ClusterTask
      params:
      - name: app-name
        value: $(params.app-name)
      - name: build-type
        value: $(params.build-type)
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: git-checkout
        value: $(params.git-checkout)
      - name: clone-type
        value: $(params.clone-type)
    - name: deploy-rolling-replace
      taskRef:
        name: deploy-rolling-replace
        kind: ClusterTask
      runAfter:
      - build
      when:
      - input: "$(params.deploy-type)"
        operator: in
        values: ["rolling-replace"]
      params:
      - name: app-name
        value: $(params.app-name)
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: git-checkout
        value: $(params.git-checkout)
      - name: clone-type
        value: $(params.clone-type)
      - name: config-git-path
        value: $(params.config-git-path)
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: trusted-ca
    labels:
      config.openshift.io/inject-trusted-cabundle: 'true'
