apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-task-2
spec:
  params:
  - name: greeting
    type: string
    default: "world"
    description: Greeting Name
  steps:
  - name: hello
    image: quay.io/buildah/stable:latest
    imagePullPolicy: IfNotPresent
    script: |
      #!/bin/bash
      echo "Hello $(params.greeting)"
  - name: goodbye
    image: quay.io/buildah/stable:latest
    imagePullPolicy: IfNotPresent
    script: |
      #!/bin/bash
      echo "Good Bye $(params.greeting)"
