apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-pod
spec:
  params:
  - name: app-name
    type: string
    description: The application name
  steps:
  - name: create-pod
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli
    imagePullPolicy: IfNotPresent
    script: |
      cat << EOF | oc apply -f -
      apiVersion: v1
      kind: Pod
      metadata:
        name: $(params.app-name)-pod
      spec:
        restartPolicy: Never
        containers:
        - name: $(params.app-name)-container
          image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.app-name):latest
      EOF
